name: 'test_project'
version: '1.0.0'
config-version: 2

profile: 'test_project' # 'test_project_2' to run for prod

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  test_project:
    example:
      +materialized: view
      +schema: example