name: Run CI/CD
on:
  pull_request:

jobs:
  run_dbt_check:
    env:
      PR_NUMBER: ${{ github.event.number }}
      GH_REPO: ${{ github.event.repository.name }}
      GH_ORG: ${{ github.event.pull_request.head.repo.owner.login }}
    runs-on: ubuntu-latest
    name: Template for Running Row/Column checks against DBT models in Bigquery
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print Env Vars
        run: |
        echo "Listing out all vars..."
        #           echo "GCP_TOKEN: ${{ secrets.GCP_TOKEN }}"
        #           echo "GH_TOKEN: ${{ secrets.GH_TOKEN }}"
        echo "PR_NUMBER: $PR_NUMBER"
        echo "GH_REPO: $GH_REPO"
        echo "GH_ORG: $GH_ORG"
        'echo "{{ secrets.GCP_TOKEN }}" > GCP_TOKEN'
        'echo "{{ secrets.GH_TOKEN }}" > GH_TOKEN'
      - name: Test Row/Column DBT BQ Checks
        uses: org-not-included/dbt_table_diff@v11
        with:
          GCP_TOKEN: $(cat GCP_TOKEN)
          GH_TOKEN: $(cat GH_TOKEN)
          PR_NUMBER: $PR_NUMBER
          GH_REPO: $GH_REPO
          GH_ORG: $GH_ORG
          dev_prefix: 'dev_'
          prod_prefix: 'prod_'
          project_id: 'ultimate-bit-359101'
          DBT_PROFILE_FILE: "profile.yml"